CXX ?= g++

# Optional compiler cache (huge speedup on rebuilds)
CCACHE := $(shell command -v ccache 2>/dev/null)
ifneq ($(strip $(CCACHE)),)
	CXX := $(CCACHE) $(CXX)
endif

# Common flags
CXXFLAGS ?= -std=c++17 -O2
CPPFLAGS ?= -Isrc
LDFLAGS  ?=
LDLIBS   ?=

# Incremental build output
BUILD_DIR ?= build

# Server deps
INGAME_SERVER_BIN := ingame_server_demo
INGAME_SERVER_SRCS := \
	src/ingame_server/main.cpp \
	src/ingame_server/core/GameServer.cpp \
	src/ingame_server/database/MatchRecorder.cpp \
	src/common/network/TCPSocket.cpp \
	src/common/network/TCPSocketUtils.cpp

# We use autogenerated dependency files (.d) to track headers.
# This avoids full rebuilds when unrelated headers change.

INGAME_CLI_BIN := ingame_cli_client
INGAME_CLI_SRCS := \
	src/client/game_main.cpp \
	src/common/network/TCPSocket.cpp \
	src/common/network/TCPSocketUtils.cpp

SERVICE_SERVER_BIN := service_server_app
SERVICE_SERVER_SRCS := \
	src/service_server/main.cpp \
	src/service_server/core/ServiceServer.cpp \
	src/service_server/logic/AuthServer.cpp \
	src/service_server/database/DatabaseServer.cpp \
	src/service_server/database/UserDAO.cpp \
	src/common/network/TCPSocket.cpp \
	src/common/network/TCPSocketUtils.cpp

# Client deps (SDL)
CLIENT_BIN := net_game_client
CLIENT_SRCS := \
	src/client/net_game_main.cpp \
	src/client/core/Game.cpp \
	src/client/core/InputHandler.cpp \
	src/client/core/StateMachine.cpp \
	src/client/core/TextureManager.cpp \
	src/client/core/Window.cpp \
	src/client/network/ClientSocket.cpp \
	src/client/scenes/SceneGame.cpp \
	src/client/scenes/TerminalScene.cpp \
	src/client/ui/Button.cpp \
	src/client/ui/Text.cpp \
	src/client/ui/TextInput.cpp \
	src/common/network/TCPSocket.cpp \
	src/common/network/TCPSocketUtils.cpp

SERVICE_CLIENT_BIN := service_client
SERVICE_CLIENT_SRCS := \
	src/client/service_client_main.cpp \
	src/client/core/Game.cpp \
	src/client/core/InputHandler.cpp \
	src/client/core/StateMachine.cpp \
	src/client/core/TextureManager.cpp \
	src/client/core/Window.cpp \
	src/client/network/ClientSocket.cpp \
	src/client/scenes/SceneLogin.cpp \
	src/client/scenes/SceneRegister.cpp \
	src/client/scenes/SceneDashboard.cpp \
	src/client/scenes/SceneViewProfile.cpp \
	src/client/scenes/SceneGame.cpp \
	src/client/scenes/TerminalScene.cpp \
	src/client/ui/Button.cpp \
	src/client/ui/Text.cpp \
	src/client/ui/TextInput.cpp \
	src/common/network/TCPSocket.cpp \
	src/common/network/TCPSocketUtils.cpp

SDL_CFLAGS := $(shell pkg-config --cflags sdl2 SDL2_image SDL2_ttf 2>/dev/null)
SDL_LIBS   := $(shell pkg-config --libs   sdl2 SDL2_image SDL2_ttf 2>/dev/null)
PQXX_LIBS  := -lpqxx -lpq

.PHONY: all server client service_server service_client ingame_cli clean dev

all: server client service_server service_client ingame_cli

# Faster local dev build: less optimization, more debug symbols.
dev: CXXFLAGS := -std=c++17 -O0 -g
dev: all

server: $(INGAME_SERVER_BIN)
client: $(CLIENT_BIN)
service_server: $(SERVICE_SERVER_BIN)
service_client: $(SERVICE_CLIENT_BIN)
ingame_cli: $(INGAME_CLI_BIN)

INGAME_SERVER_OBJDIR := $(BUILD_DIR)/obj/ingame_server
INGAME_SERVER_OBJS := $(patsubst src/%.cpp,$(INGAME_SERVER_OBJDIR)/%.o,$(INGAME_SERVER_SRCS))

$(INGAME_SERVER_BIN): $(INGAME_SERVER_OBJS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -pthread $(INGAME_SERVER_OBJS) $(LDFLAGS) $(LDLIBS) $(PQXX_LIBS) -o $@

INGAME_CLI_OBJDIR := $(BUILD_DIR)/obj/ingame_cli
INGAME_CLI_OBJS := $(patsubst src/%.cpp,$(INGAME_CLI_OBJDIR)/%.o,$(INGAME_CLI_SRCS))

$(INGAME_CLI_BIN): $(INGAME_CLI_OBJS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -pthread $(INGAME_CLI_OBJS) $(LDFLAGS) $(LDLIBS) -o $@

SERVICE_SERVER_OBJDIR := $(BUILD_DIR)/obj/service_server
SERVICE_SERVER_OBJS := $(patsubst src/%.cpp,$(SERVICE_SERVER_OBJDIR)/%.o,$(SERVICE_SERVER_SRCS))

$(SERVICE_SERVER_BIN): $(SERVICE_SERVER_OBJS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -pthread $(SERVICE_SERVER_OBJS) $(LDFLAGS) $(LDLIBS) $(PQXX_LIBS) -o $@

CLIENT_OBJDIR := $(BUILD_DIR)/obj/client
CLIENT_OBJS := $(patsubst src/%.cpp,$(CLIENT_OBJDIR)/%.o,$(CLIENT_SRCS))

$(CLIENT_BIN): $(CLIENT_OBJS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -pthread $(CLIENT_OBJS) $(SDL_LIBS) $(LDFLAGS) $(LDLIBS) -o $@

SERVICE_CLIENT_OBJDIR := $(BUILD_DIR)/obj/service_client
SERVICE_CLIENT_OBJS := $(patsubst src/%.cpp,$(SERVICE_CLIENT_OBJDIR)/%.o,$(SERVICE_CLIENT_SRCS))

$(SERVICE_CLIENT_BIN): $(SERVICE_CLIENT_OBJS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -pthread $(SERVICE_CLIENT_OBJS) $(SDL_LIBS) $(LDFLAGS) $(LDLIBS) -o $@

# Per-target compile rules (keep flags correct; SDL-only targets get SDL_CFLAGS)
$(INGAME_SERVER_OBJDIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MMD -MP -pthread -c $< -o $@

$(INGAME_CLI_OBJDIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MMD -MP -pthread -c $< -o $@

$(SERVICE_SERVER_OBJDIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MMD -MP -pthread -c $< -o $@

$(CLIENT_OBJDIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MMD -MP -pthread $(SDL_CFLAGS) -c $< -o $@

$(SERVICE_CLIENT_OBJDIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MMD -MP -pthread $(SDL_CFLAGS) -c $< -o $@

clean:
	rm -f $(INGAME_SERVER_BIN) $(CLIENT_BIN) $(SERVICE_SERVER_BIN) $(SERVICE_CLIENT_BIN) $(INGAME_CLI_BIN)
	rm -rf $(BUILD_DIR)

# Pull in header dependencies
-include $(INGAME_SERVER_OBJS:.o=.d)
-include $(INGAME_CLI_OBJS:.o=.d)
-include $(SERVICE_SERVER_OBJS:.o=.d)
-include $(CLIENT_OBJS:.o=.d)
-include $(SERVICE_CLIENT_OBJS:.o=.d)
